#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_INPUT_FINGERPRINT_DETECT)	+= fingerprint_detect/
obj-$(CONFIG_INPUT_FPC1020)		+= fpc1020_tee.o
obj-$(CONFIG_INPUT_GOODIX_FP)		+= goodix_fp/
